// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
   return web;
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyA5Np4-kz2lyEa7CG6QzOQj5rUoH-NcMCM",
    authDomain: "controle-gasto-4f6f8.firebaseapp.com",
    projectId: "controle-gasto-4f6f8",
    storageBucket: "controle-gasto-4f6f8.appspot.com",
    messagingSenderId: "157263105669",
    appId: "1:157263105669:web:d4c4af3f2aace0c26b23ec",
    measurementId: "G-RTR8BN7188"
  );

 
}
